###########################
# Todo
# Create TGCO user for management
# Create SystemD
# test if database generation is required
#########################

- name: generating TGCO User
  user:
    name: "tgco"
    shell: "{{ item.shell | default('/bin/bash') }}"
    system: True
    comment: "the great code off user"
    update_password: on_create
    password: "{{ tgco_secret_key | password_hash('sha512') }}"

- name: Create The-Great-code-off-directory
  ansible.builtin.file:
    path: "{{ tgco_path }}"
    group: tgco
    owner: tgco
    state: directory
    mode: '0755'

- name: setting up files
  copy:
    src: files/
    dest: "{{ tgco_path }}/"
    owner: tgco
    group: tgco

- name: Setting up TGCO setings
  template:
    src: settings.py.j2
    dest: "{{ tgco_path }}/performance/settings.py"
    owner: tgco
    group: tgco
    mode: '0644'

- name: Generating TGCO Makefile
  copy:
    dest: "{{ tgco_path }}/Makefile"
    force: yes
    group: tgco
    owner: tgco
    mode: '0644'
    content: |
      tgco:
              if test -f "{{ tgco_path }}/db.sqlite3";then \
                      {{ tgco_path }}/.tgco_env/bin/gunicorn performance.wsgi --bind 127.0.0.1:{{ tgco_port }}; \
              else \
                      {{ tgco_path }}/.tgco_env/bin/python manage.py migrate api; \
                      {{ tgco_path }}/.tgco_env/bin/gunicorn performance.wsgi --bind 127.0.0.1:{{ tgco_port }}; \
              fi

    
- name: Install tgco requirements
  pip: 
    requirements: "{{ tgco_path }}/requirements.txt"
    virtualenv: "{{ tgco_path }}/.tgco_env"
  become: True
  become_user: tgco

    #virtualenv_python: python3.11.0 

- name: deploy tgco unit
  template:
    src: tgco.service.j2
    dest: /etc/systemd/system/tgco.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - systemd daemon reload
    - start the great code off
    - restart the great code off

- name: Enable tgco unit
  systemd:
    name: tgco.service
    enabled: yes
