###########################
# Todo
# Create TGCO user for management
# Create SystemD
# test if database generation is required
#########################

- name: generating TGCO User
  user:
    name: "tgco"
    shell: "{{ item.shell | default('/bin/bash') }}"
    system: True
    comment: "the great code off user"
    update_password: on_create
    password: "{{ tgco_secret_key | password_hash('sha512') }}"

- name: Create The-Great-code-off-directory
  ansible.builtin.file:
    path: "{{ tgco_path }}"
    state: directory
    mode: '0755'

- name: stting up files
  copy:
    src: files/
    dest: "{{ tgco_path }}/"
    owner: tgco
    group: tgco

- name: Setting up TGCO setings
  template:
    src: settings.py.j2
    dest: "{{ tgco_path }}/performance/settings.py"
    owner: tgco
    group: tgco
    mode: '0644'
  
- name: Install tgco requirements
  pip: 
    requirements: "{{ tgco_path }}/requirements.txt"
    virtualenv: "{{ tgco_path }}/.tgco_env"
    #virtualenv_python: python3.11.0 

- name: deploy tgco unit
  template:
    src: tgco.service.j2
    dest: /etc/systemd/system/tgco.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - systemd daemon reload
    - start the great code off
    - restart the great code off

- name: Enable tgco unit
  systemd:
    name: tgco.service
    enabled: yes
