# Generated by Django 4.1.2 on 2022-10-18 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_entry_function"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="function",
            new_name="user",
        ),
    ]
