# Generated by Django 4.0.4 on 2022-10-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_function_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='memory',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='complexity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
