tgco:
        
        ifneq ("$(wildcard $({{ tgco_path }}/db.sqlite3))","")
		    gunicorn performance.wsgi --bind 127.0.0.1:{{ tgco_port }}
        else
            python manage.py migrate api
		    gunicorn performance.wsgi --bind 127.0.0.1:{{ tgco_port }}
        endif