tgco:
        if test -f "{{ tgco_path }}/db.sqlite3";then \
                {{ tgco_path }}/.tgco_env/bin/gunicorn performance.wsgi --bind 127.0.0.1:{{ tgco_port }}; \
        else \
                {{ tgco_path }}/.tgco_env/bin/python manage.py migrate api; \
                {{ tgco_path }}/.tgco_env/bin/gunicorn performance.wsgi --bind 127.0.0.1:{{ tgco_port }}; \
        fi
